language: node_js
node_js:
- 10.7.0
sudo: required
cache:
  yarn: true
  directories:
  - node_modules
script:
- yarn ami
notifications:
  slack: fnndsc:UohaXDsjFDVqZj5IfdC88XRa
deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    repo: FNNDSC/ami
    branch: master
    tags: false
